### ISSUE TITLE
Helm Release Error

### ISSUE THREAD

**Issue by devenes** [Josh-Tracy/Terraform-Helm-EKS-Jenkins#2]
Helm Release Terraform module is not working.

**Comment by suba23** [comment]
same module cluster is not reachable

**Comment by devenes** [comment]
Still, the error is not fixed.

**Comment by Josh-Tracy** [comment]
> Helm Release Terraform module is not working.

I got around updating this to the latest versions of providers and modules. I'm not sure what the issue you were facing was, but is more than likely fixed now. Please provide some information next time you encounter an issue.
